apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-waypoints-monitor
  namespace: bookinfo
  labels:
    k8s-app: waypoint-monitor
    openshift.io/user-monitoring: "true"
spec:
  selector:
    matchExpressions:
      - key: gateway.networking.k8s.io/gateway-name
        operator: In
        values:
          - productpage-waypoint
          - reviews-waypoint
          - ratings-waypoint
          - details-waypoint
  podMetricsEndpoints:
    - path: /stats/prometheus
      port: http-envoy-prom
      interval: 30s

