apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
  namespace: observability
spec:
  managementState: Managed
  replicationFactor: 1
  retention:
    global: 
      traces: "48h"
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
  storage:
    secret:
      name: tempo-demo-s3
      type: s3
  storageSize: 10Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m