apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: kiali-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace