apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
spec:
  monDataDirHostPath: '' 
  manageNodes: false
  multiCloudGateway:
    reconcileStrategy: standalone
    dbStorageClassName: gp3-csi
  storageDeviceSets:
    - name: ocs-deviceset
      count: 1
      replica: 3
      resources:
        requests:
          storage: 100Gi
      placement: {}
      portable: true
      dataPVCTemplate:
        spec:
          storageClassName: gp3-csi
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 100Gi